replicaCount: 1

image:
  repository: 525530758671.dkr.ecr.ap-south-1.amazonaws.com/myapp
  tag: "54"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

containerPort: 5000

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

autoscaling:
  enabled: false

serviceAccount:
  create: false

livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5

ingress:
  enabled: false

nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
